Repository HYF-Class20/agile-development-group3-all-about-tree, pull requests merged in 2023-04, with the labels that each got.

#11 modified planning/communication.md
  planning/communication.md
  planning/constraints.md
Labels: communication

#10 Design
  .cspell.json
  planning/design.md
  planning/user-personas.md
Labels: group, md, communication, collaboration, phase1

#14 updating planning/communication.md
  planning/communication.md
Labels: communication

#20 Add readme
  README.md
Labels: md, collaboration

#23 Code
  README.md
  code/happy-tree.jpg
  code/index.html
  code/styles.css
  src/screenshot.png
  src/trees.png
Labels: team, communication, collaboration
